---
- name: 'Windows Patch Servers'
  hosts: all
  gather_facts: True
  vars:
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_transport: ntlm
  roles:
    - win_patch
